from __future__ import annotations

from typing import Protocol

from atlasflow.knowledge.domain import (
    DocumentVersion,
    IndexGeneration,
    IngestionJob,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeFilter,
    KnowledgeSpace,
)


class KnowledgeRepository(Protocol):
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def create_space(self, space: KnowledgeSpace) -> KnowledgeSpace: ...
    async def list_spaces(self) -> list[KnowledgeSpace]: ...
    async def get_space(self, space_id_or_slug: str) -> KnowledgeSpace | None: ...
    async def update_space(self, space: KnowledgeSpace) -> KnowledgeSpace: ...
    async def create_document(
        self, document: KnowledgeDocument
    ) -> KnowledgeDocument: ...
    async def update_document(
        self, document: KnowledgeDocument
    ) -> KnowledgeDocument: ...
    async def get_document(self, document_id: str) -> KnowledgeDocument | None: ...
    async def find_document(
        self, space_id: str, source_id: str
    ) -> KnowledgeDocument | None: ...
    async def list_documents(self, space_id: str) -> list[KnowledgeDocument]: ...
    async def purge_document(self, document_id: str) -> None: ...
    async def create_version(self, version: DocumentVersion) -> DocumentVersion: ...
    async def update_version(self, version: DocumentVersion) -> DocumentVersion: ...
    async def get_version(self, version_id: str) -> DocumentVersion | None: ...
    async def list_versions(self, document_id: str) -> list[DocumentVersion]: ...
    async def create_generation(
        self, generation: IndexGeneration
    ) -> IndexGeneration: ...
    async def get_generation(self, generation_id: str) -> IndexGeneration | None: ...
    async def active_generation(self, space_id: str) -> IndexGeneration | None: ...
    async def activate_generation(self, generation_id: str) -> IndexGeneration: ...
    async def replace_chunks(
        self, version_id: str, chunks: list[KnowledgeChunk]
    ) -> None: ...
    async def get_chunks(self, chunk_ids: list[str]) -> list[KnowledgeChunk]: ...
    async def count_version_chunks(
        self, version_id: str, kind: str = "child"
    ) -> int: ...
    async def list_searchable_chunks(
        self, space_id: str, filters: KnowledgeFilter | None = None
    ) -> list[KnowledgeChunk]: ...
    async def create_job(self, job: IngestionJob) -> IngestionJob: ...
    async def update_job(self, job: IngestionJob) -> IngestionJob: ...
    async def get_job(self, job_id: str) -> IngestionJob | None: ...
    async def list_jobs(self, space_id: str | None = None) -> list[IngestionJob]: ...
    async def claim_job(self, job_id: str | None = None) -> IngestionJob | None: ...
    async def count_chunks(self) -> int: ...
